CC = g++

all: tut2_complete tut2_start_here

tut2_start_here:
	$(CC) --std=c++11 ../start_here/tut2.cpp -lpoplar -lpopops -lpoputil -o tut2_start_here

tut2_complete:
	$(CC) --std=c++11 ../complete/tut2_complete.cpp -lpoplar -lpopops -lpoputil -o tut2_complete

clean:
	rm -f tut2_complete tut2_start_here