CC = g++

all: tut3_complete tut3_start_here

tut3_start_here:
	$(CC) --std=c++11 ../start_here/tut3.cpp -lpoplar -o tut3_start_here

tut3_complete:
	$(CC) --std=c++11 ../complete/tut3_complete.cpp -lpoplar -o ../complete/tut3_complete

clean:
	rm -f ../complete/tut3_complete tut3_start_here