# Copyright (c) 2021 Graphcore Ltd. All rights reserved.

import random
import tensorflow as tf
import numpy as np
from tensorflow.python.ipu.utils import reset_ipu_seed


def set_seed(seed):
    if seed is not None:
        random.seed(seed)
        # Set other seeds to different values for extra safety.
        # The new seeds are defined indirectly by the main seed,
        # since they are generated by the seeded random function.
        tf.random.set_seed(random.randint(0, 2**32 - 1))
        np.random.seed(random.randint(0, 2**32 - 1))
        reset_ipu_seed(random.randint(-2**16, 2**16 - 1), experimental_identical_replicas=True)
