CC = g++

all:  ../complete/tut3_complete

 ../complete/tut3_complete: ../complete/tut3_complete.cpp
	$(CC) --std=c++11 ../complete/tut3_complete.cpp -lpoplar -o ../complete/tut3_complete

clean:
	rm -f ../complete/tut3_complete
