CC = g++

all: tut4_complete tut4_start_here

tut4_start_here:
	$(CC) --std=c++11 ../start_here/tut4.cpp -lpoplar -lpopops -lpoplin -lpoputil -o tut4_start_here

tut4_complete:
	$(CC) --std=c++11 ../complete/tut4_complete.cpp -lpoplar -lpopops -lpoplin -lpoputil -o tut4_complete

clean:
	rm -f tut4_complete tut4_start_here